### PR TITLE
defaultText fix for dropdownList method

### PR DESCRIPTION
**Pull request by miradnan**
Use the placeholder value as defaultText for dropdownList method

### CODE REVIEW

**Comment by zelenin** [comment]
Where did you find placeholder attribute in select/dropdown?

**Comment by miradnan** [comment]
Yes

Zelenin\yii\SemanticUI\widgets\ActiveField

You need to append ‘defaultText’ just like below.



Best Regards,

Mir Adnan
miradnanali@gmail.com

**Comment by zelenin** [comment]
Where did you find a placeholder attribute in select/dropdown?

**Comment by miradnan** [comment]
I found it in Zelenin\yii\SemanticUI\widgets\ActiveField dropDownList method.

**Comment by zelenin** [comment]
A html select hasn't a placeholder. I will not add it. You shoud use a native api for it (see semantic ui docs).

**Comment by miradnan** [comment]
Okay. How do I add defaultText then?

**Comment by zelenin** [comment]
Ah, I see. Dropdown is not select and has not a default option.
Ok, use options like here https://github.com/zelenin/yii2-semantic-ui/blob/master/widgets/ActiveField.php#L91 and I will merge it
```php
$defaultText = ArrayHelper::remove($options, 'defaultText', '');
```

**Comment by miradnan** [comment]
Done

**Comment by zelenin** [comment]
Thanks!

**Comment by miradnan** [comment]
Awesome! Thanks

**Pull request merged**
